// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getAvailableVersions() : Promise<Result<Version[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_versions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Launch Minecraft using a saved profile.
 */
async downloadVersionAndRun(profileId: string, username: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_version_and_run", { profileId, username }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProfiles() : Promise<Profile[]> {
    return await TAURI_INVOKE("list_profiles");
},
async saveProfile(profile: Profile) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_profile", { profile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteProfile(id: string, deleteFolder: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_profile", { id, deleteFolder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async duplicateProfile(id: string) : Promise<Result<Profile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("duplicate_profile", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLastProfileId() : Promise<string | null> {
    return await TAURI_INVOKE("get_last_profile_id");
},
async setLastProfileId(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_last_profile_id", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<LauncherSettings> {
    return await TAURI_INVOKE("get_settings");
},
async updateSettings(settings: LauncherSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetSettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportProfile(id: string, destPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_profile", { id, destPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importProfile(zipPath: string) : Promise<Result<Profile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_profile", { zipPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMods(profileId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_mods", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listShaders(profileId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_shaders", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listResourcePacks(profileId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_resource_packs", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModloaderVersions(modloader: string, mcVersion: string) : Promise<Result<ModloaderVersion[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_modloader_versions", { modloader, mcVersion }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAuthMode() : Promise<boolean> {
    return await TAURI_INVOKE("get_auth_mode");
},
async startMsLogin() : Promise<Result<DeviceCodeInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_ms_login") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pollMsLogin() : Promise<Result<MinecraftAccount, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("poll_ms_login") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActiveAccount() : Promise<MinecraftAccount | null> {
    return await TAURI_INVOKE("get_active_account");
},
async listAccounts() : Promise<MinecraftAccount[]> {
    return await TAURI_INVOKE("list_accounts");
},
async switchAccount(uuid: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("switch_account", { uuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async logoutAccount(uuid: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("logout_account", { uuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshActiveAccount() : Promise<Result<MinecraftAccount, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_active_account") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectSystemJavas() : Promise<JavaInstall[]> {
    return await TAURI_INVOKE("detect_system_javas");
},
async downloadJava(version: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_java", { version }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRequiredJavaVersion(mcVersion: string) : Promise<number> {
    return await TAURI_INVOKE("get_required_java_version", { mcVersion });
},
async getLocalJavaVersion(path: string) : Promise<number | null> {
    return await TAURI_INVOKE("get_local_java_version", { path });
},
async saveLogFile(path: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_log_file", { path, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchModpacks(query: string, offset: number) : Promise<Result<ModpackSearchResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_modpacks", { query, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModpackVersions(projectId: string) : Promise<Result<ModpackVersion[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_modpack_versions", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installModpack(projectId: string, versionId: string, modpackName: string) : Promise<Result<Profile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_modpack", { projectId, versionId, modpackName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkModpackUpdate(profileId: string) : Promise<Result<ModpackVersion | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_modpack_update", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateModpack(profileId: string) : Promise<Result<Profile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_modpack", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSystemMemoryMb() : Promise<number> {
    return await TAURI_INVOKE("get_system_memory_mb");
},
async searchModrinth(query: string, projectType: string, gameVersion: string, modloader: string, offset: number) : Promise<Result<ModpackSearchResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_modrinth", { query, projectType, gameVersion, modloader, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installModrinthContent(projectId: string, versionId: string, gameDir: string, subfolder: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_modrinth_content", { projectId, versionId, gameDir, subfolder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type DeviceCodeInfo = { user_code: string; verification_uri: string; message: string }
export type InstalledModpackInfo = { project_id: string; version_id: string; version_name: string }
export type JavaInstall = { path: string; version: number }
export type LauncherSettings = { theme: string; language: string; accent_color?: string; font_family?: string; ui_style?: string; ui_scale?: number; close_on_launch: boolean; default_resolution_width: number; default_resolution_height: number; fullscreen: boolean; default_jvm_args: string; custom_java_path: string | null; game_root_directory: string; http_proxy: string | null; verbose_logging: boolean; show_snapshots: boolean; show_old_beta: boolean; show_old_alpha: boolean }
export type MinecraftAccount = { uuid: string; username: string; access_token: string; refresh_token: string; skin_url: string | null; active: boolean }
export type ModloaderVersion = { version: string; stable: boolean }
export type ModpackSearchResult = { project_id: string; slug: string; title: string; description: string; icon_url: string; downloads: number; author: string; categories: string[]; latest_mc_version: string }
export type ModpackVersion = { version_id: string; name: string; version_number: string; mc_versions: string[]; loaders: string[]; download_url: string; file_size: number; date_published: string }
export type Profile = { id: string; name: string; version: string; 
/**
 * Minecraft manifest URL
 */
version_url: string; 
/**
 * "none" | "fabric" | "forge" | "neoforge"
 */
modloader: string; modloader_version: string | null; game_dir: string; java_path: string | null; jvm_args: string; resolution: Resolution; modpack_info?: InstalledModpackInfo | null }
export type Resolution = { width: number; height: number }
export type Version = { id: string; type: string; url: string; time: string; releaseTime: string; sha1: string; complianceLevel: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
